module;
#define THRUST_HOST_SYSTEM   THRUST_HOST_SYSTEM_CPP
#define THRUST_DEVICE_SYSTEM THRUST_DEVICE_SYSTEM_TBB
#undef in
#undef self
#include <thrust/addressof.h>
#include <thrust/adjacent_difference.h>
#include <thrust/advance.h>
#include <thrust/allocate_unique.h>
#include <thrust/binary_search.h>
#include <thrust/complex.h>
#include <thrust/copy.h>
#include <thrust/count.h>
#include <thrust/device_allocator.h>
#include <thrust/device_delete.h>
#include <thrust/device_free.h>
#include <thrust/device_make_unique.h>
#include <thrust/device_malloc_allocator.h>
#include <thrust/device_malloc.h>
#include <thrust/device_new_allocator.h>
#include <thrust/device_new.h>
#include <thrust/device_ptr.h>
#include <thrust/device_reference.h>
#include <thrust/device_vector.h>
#include <thrust/distance.h>
#include <thrust/equal.h>
#include <thrust/execution_policy.h>
#include <thrust/extrema.h>
#include <thrust/fill.h>
#include <thrust/find.h>
#include <thrust/for_each.h>
#include <thrust/functional.h>
#include <thrust/gather.h>
#include <thrust/generate.h>
#include <thrust/host_vector.h>
#include <thrust/inner_product.h>
#include <thrust/iterator/constant_iterator.h>
#include <thrust/iterator/counting_iterator.h>
#include <thrust/iterator/discard_iterator.h>
#include <thrust/iterator/iterator_adaptor.h>
#include <thrust/iterator/iterator_categories.h>
#include <thrust/iterator/iterator_facade.h>
#include <thrust/iterator/iterator_traits.h>
#include <thrust/iterator/offset_iterator.h>
#include <thrust/iterator/permutation_iterator.h>
#include <thrust/iterator/retag.h>
#include <thrust/iterator/reverse_iterator.h>
#include <thrust/iterator/shuffle_iterator.h>
#include <thrust/iterator/strided_iterator.h>
#include <thrust/iterator/tabulate_output_iterator.h>
#include <thrust/iterator/transform_input_output_iterator.h>
#include <thrust/iterator/transform_iterator.h>
#include <thrust/iterator/transform_output_iterator.h>
#include <thrust/iterator/zip_iterator.h>
#include <thrust/logical.h>
#include <thrust/memory.h>
#include <thrust/merge.h>
#include <thrust/mismatch.h>
#include <thrust/mr/allocator.h>
#include <thrust/mr/device_memory_resource.h>
#include <thrust/mr/disjoint_pool.h>
#include <thrust/mr/disjoint_sync_pool.h>
#include <thrust/mr/disjoint_tls_pool.h>
#include <thrust/mr/fancy_pointer_resource.h>
#include <thrust/mr/host_memory_resource.h>
#include <thrust/mr/memory_resource.h>
#include <thrust/mr/new.h>
#include <thrust/mr/polymorphic_adaptor.h>
#include <thrust/mr/pool_options.h>
#include <thrust/mr/pool.h>
#include <thrust/mr/sync_pool.h>
#include <thrust/mr/tls_pool.h>
#include <thrust/mr/universal_memory_resource.h>
#include <thrust/mr/validator.h>
#include <thrust/pair.h>
#include <thrust/partition.h>
#include <thrust/per_device_resource.h>
#include <thrust/random.h>
#include <thrust/random/discard_block_engine.h>
#include <thrust/random/linear_congruential_engine.h>
#include <thrust/random/linear_feedback_shift_engine.h>
#include <thrust/random/normal_distribution.h>
#include <thrust/random/subtract_with_carry_engine.h>
#include <thrust/random/uniform_int_distribution.h>
#include <thrust/random/uniform_real_distribution.h>
#include <thrust/random/xor_combine_engine.h>
#include <thrust/reduce.h>
#include <thrust/remove.h>
#include <thrust/replace.h>
#include <thrust/reverse.h>
#include <thrust/scan.h>
#include <thrust/scatter.h>
#include <thrust/sequence.h>
#include <thrust/set_operations.h>
#include <thrust/shuffle.h>
#include <thrust/sort.h>
#include <thrust/swap.h>
#include <thrust/system_error.h>
#include <thrust/system/cpp/execution_policy.h>
#include <thrust/system/cpp/memory_resource.h>
#include <thrust/system/cpp/memory.h>
#include <thrust/system/cpp/pointer.h>
#include <thrust/system/cpp/vector.h>
#include <thrust/system/error_code.h>
#include <thrust/system/omp/execution_policy.h>
#include <thrust/system/omp/memory_resource.h>
#include <thrust/system/omp/memory.h>
#include <thrust/system/omp/pointer.h>
#include <thrust/system/omp/vector.h>
#include <thrust/system/system_error.h>
#include <thrust/system/tbb/execution_policy.h>
#include <thrust/system/tbb/memory_resource.h>
#include <thrust/system/tbb/memory.h>
#include <thrust/system/tbb/pointer.h>
#include <thrust/system/tbb/vector.h>
#include <thrust/tabulate.h>
#include <thrust/transform_reduce.h>
#include <thrust/transform_scan.h>
#include <thrust/transform.h>
#include <thrust/tuple.h>
#include <thrust/type_traits/integer_sequence.h>
#include <thrust/type_traits/is_contiguous_iterator.h>
#include <thrust/type_traits/is_execution_policy.h>
#include <thrust/type_traits/is_operator_less_or_greater_function_object.h>
#include <thrust/type_traits/is_operator_plus_function_object.h>
#include <thrust/type_traits/is_trivially_relocatable.h>
#include <thrust/type_traits/logical_metafunctions.h>
#include <thrust/type_traits/unwrap_contiguous_iterator.h>
#include <thrust/uninitialized_copy.h>
#include <thrust/uninitialized_fill.h>
#include <thrust/unique.h>
#include <thrust/universal_allocator.h>
#include <thrust/universal_ptr.h>
#include <thrust/universal_vector.h>
#include <thrust/version.h>
#include <thrust/zip_function.h>

export module thrust;
import        std;
import        cuda;

export namespace thrust
{

}