#pragma once

/// Include

#include "int/abs.ipp"
#include "int/log_log2_log10_ln.ipp"
#include "int/mod.ipp"
#include "int/pow_sqrt_exp_exp2.ipp"
#include "float/abs.ipp"
#include "float/floor_ceil_round.ipp"
#include "float/log_log2_log10_ln.ipp"
#include "float/mod.ipp"
#include "float/pow_sqrt_exp_exp2.ipp"
#include "angle/abs.ipp"
#include "angle/arcsin_arccos_arctan_arccot_arcsec_arccsc.ipp"
#include "angle/mod.ipp"
#include "angle/sin_cos_tan_cot_sec_csc.ipp"
#include "complex/abs_norm.ipp"
#include "complex/conj.ipp"
#include "complex/floor_ceil_round.ipp"
#include "complex/log_log2_log10_ln.ipp"
#include "complex/pow_sqrt_exp_exp2.ipp"
#include "polar/abs_norm.ipp"
#include "polar/conj.ipp"
#include "polar/log_log2_log10_ln.ipp"
#include "polar/pow_sqrt_exp_exp2.ipp"
#include "std/common_type.ipp"
#include "std/numeric_limits.ipp"