module;
third_party/git/icu/icu4c/source/common/rbbi_cache.h
third_party/git/icu/icu4c/source/common/unisetspan.h
third_party/git/icu/icu4c/source/common/localeprioritylist.h
third_party/git/icu/icu4c/source/common/ureslocs.h
third_party/git/icu/icu4c/source/common/propsvec.h
third_party/git/icu/icu4c/source/common/rbbinode.h
third_party/git/icu/icu4c/source/common/udatamem.h
third_party/git/icu/icu4c/source/common/ucol_swp.h
third_party/git/icu/icu4c/source/common/umutex.h
third_party/git/icu/icu4c/source/common/locmap.h
third_party/git/icu/icu4c/source/common/uvector.h
third_party/git/icu/icu4c/source/common/uniquecharstr.h
third_party/git/icu/icu4c/source/common/uvectr32.h
third_party/git/icu/icu4c/source/common/servnotf.h
third_party/git/icu/icu4c/source/common/locdistance.h
third_party/git/icu/icu4c/source/common/ustr_imp.h
third_party/git/icu/icu4c/source/common/servloc.h
third_party/git/icu/icu4c/source/common/ucln.h
third_party/git/icu/icu4c/source/common/unormimp.h
third_party/git/icu/icu4c/source/common/unifiedcache.h
third_party/git/icu/icu4c/source/common/localefallback_data.h
third_party/git/icu/icu4c/source/common/loclikelysubtags.h
third_party/git/icu/icu4c/source/common/emojiprops.h
third_party/git/icu/icu4c/source/common/pluralmap.h
third_party/git/icu/icu4c/source/common/uchar_props_data.h
third_party/git/icu/icu4c/source/common/uresdata.h
third_party/git/icu/icu4c/source/common/lstmbe.h
third_party/git/icu/icu4c/source/common/cpputils.h
third_party/git/icu/icu4c/source/common/rbbidata.h
third_party/git/icu/icu4c/source/common/uassert.h
third_party/git/icu/icu4c/source/common/usc_impl.h
third_party/git/icu/icu4c/source/common/uelement.h
third_party/git/icu/icu4c/source/common/utrie2.h
third_party/git/icu/icu4c/source/common/dictbe.h
third_party/git/icu/icu4c/source/common/unicode/utf_old.h
third_party/git/icu/icu4c/source/common/unicode/ubrk.h
third_party/git/icu/icu4c/source/common/unicode/localematcher.h
third_party/git/icu/icu4c/source/common/unicode/stringpiece.h
third_party/git/icu/icu4c/source/common/unicode/ucat.h
third_party/git/icu/icu4c/source/common/unicode/stringoptions.h
third_party/git/icu/icu4c/source/common/unicode/ptypes.h
third_party/git/icu/icu4c/source/common/unicode/usetiter.h
third_party/git/icu/icu4c/source/common/unicode/errorcode.h
third_party/git/icu/icu4c/source/common/unicode/dtintrv.h
third_party/git/icu/icu4c/source/common/unicode/ucurr.h
third_party/git/icu/icu4c/source/common/unicode/icuplug.h
third_party/git/icu/icu4c/source/common/unicode/utext.h
third_party/git/icu/icu4c/source/common/unicode/edits.h
third_party/git/icu/icu4c/source/common/unicode/parsepos.h
third_party/git/icu/icu4c/source/common/unicode/urep.h
third_party/git/icu/icu4c/source/common/unicode/utf32.h
third_party/git/icu/icu4c/source/common/unicode/ustring.h
third_party/git/icu/icu4c/source/common/unicode/ubiditransform.h
third_party/git/icu/icu4c/source/common/unicode/uenum.h
third_party/git/icu/icu4c/source/common/unicode/umutablecptrie.h
third_party/git/icu/icu4c/source/common/unicode/appendable.h
third_party/git/icu/icu4c/source/common/unicode/uset.h
third_party/git/icu/icu4c/source/common/unicode/casemap.h
third_party/git/icu/icu4c/source/common/unicode/schriter.h
third_party/git/icu/icu4c/source/common/unicode/ucpmap.h
third_party/git/icu/icu4c/source/common/unicode/uldnames.h
third_party/git/icu/icu4c/source/common/unicode/uiter.h
third_party/git/icu/icu4c/source/common/unicode/docmain.h
third_party/git/icu/icu4c/source/common/unicode/uniset.h
third_party/git/icu/icu4c/source/common/unicode/udata.h
third_party/git/icu/icu4c/source/common/unicode/stringtriebuilder.h
third_party/git/icu/icu4c/source/common/unicode/chariter.h
third_party/git/icu/icu4c/source/common/unicode/umisc.h
third_party/git/icu/icu4c/source/common/unicode/uloc.h
third_party/git/icu/icu4c/source/common/unicode/utfiterator.h
third_party/git/icu/icu4c/source/common/unicode/ulocbuilder.h
third_party/git/icu/icu4c/source/common/unicode/bytestriebuilder.h
third_party/git/icu/icu4c/source/common/unicode/utrace.h
third_party/git/icu/icu4c/source/common/unicode/locdspnm.h
third_party/git/icu/icu4c/source/common/unicode/uchriter.h
third_party/git/icu/icu4c/source/common/unicode/enumset.h
third_party/git/icu/icu4c/source/common/unicode/utf.h
third_party/git/icu/icu4c/source/common/unicode/strenum.h
third_party/git/icu/icu4c/source/common/unicode/ucnv_err.h
third_party/git/icu/icu4c/source/common/unicode/bytestrie.h
third_party/git/icu/icu4c/source/common/unicode/uobject.h
third_party/git/icu/icu4c/source/common/unicode/ures.h
third_party/git/icu/icu4c/source/common/unicode/normlzr.h
third_party/git/icu/icu4c/source/common/unicode/usprep.h
third_party/git/icu/icu4c/source/common/unicode/urename.h
third_party/git/icu/icu4c/source/common/unicode/caniter.h
third_party/git/icu/icu4c/source/common/unicode/ucharstrie.h
third_party/git/icu/icu4c/source/common/unicode/unistr.h
third_party/git/icu/icu4c/source/common/unicode/rbbi.h
third_party/git/icu/icu4c/source/common/unicode/idna.h
third_party/git/icu/icu4c/source/common/unicode/unorm2.h
third_party/git/icu/icu4c/source/common/unicode/localebuilder.h
third_party/git/icu/icu4c/source/common/unicode/dbbi.h
third_party/git/icu/icu4c/source/common/unicode/bytestream.h
third_party/git/icu/icu4c/source/common/unicode/uversion.h
third_party/git/icu/icu4c/source/common/unicode/messagepattern.h
third_party/git/icu/icu4c/source/common/unicode/uidna.h
third_party/git/icu/icu4c/source/common/unicode/filteredbrk.h
third_party/git/icu/icu4c/source/common/unicode/char16ptr.h
third_party/git/icu/icu4c/source/common/unicode/symtable.h
third_party/git/icu/icu4c/source/common/unicode/ucasemap.h
third_party/git/icu/icu4c/source/common/unicode/udisplaycontext.h
third_party/git/icu/icu4c/source/common/unicode/umachine.h
third_party/git/icu/icu4c/source/common/unicode/ustringtrie.h
third_party/git/icu/icu4c/source/common/unicode/ucptrie.h
third_party/git/icu/icu4c/source/common/unicode/icudataver.h
third_party/git/icu/icu4c/source/common/unicode/uchar.h
third_party/git/icu/icu4c/source/common/unicode/unorm.h
third_party/git/icu/icu4c/source/common/unicode/ushape.h
third_party/git/icu/icu4c/source/common/unicode/unifunct.h
third_party/git/icu/icu4c/source/common/unicode/simpleformatter.h
third_party/git/icu/icu4c/source/common/unicode/ucnv_cb.h
third_party/git/icu/icu4c/source/common/unicode/locid.h
third_party/git/icu/icu4c/source/common/unicode/resbund.h
third_party/git/icu/icu4c/source/common/unicode/ubidi.h
third_party/git/icu/icu4c/source/common/unicode/uvernum.h
third_party/git/icu/icu4c/source/common/unicode/unimatch.h
third_party/git/icu/icu4c/source/common/unicode/ucnvsel.h
third_party/git/icu/icu4c/source/common/unicode/parseerr.h
third_party/git/icu/icu4c/source/common/unicode/putil.h
third_party/git/icu/icu4c/source/common/unicode/normalizer2.h
third_party/git/icu/icu4c/source/common/unicode/ucnv.h
third_party/git/icu/icu4c/source/common/unicode/ucharstriebuilder.h
third_party/git/icu/icu4c/source/common/unicode/ulocale.h
third_party/git/icu/icu4c/source/common/unicode/uconfig.h
third_party/git/icu/icu4c/source/common/unicode/utf16.h
third_party/git/icu/icu4c/source/common/unicode/brkiter.h
third_party/git/icu/icu4c/source/common/unicode/platform.h
third_party/git/icu/icu4c/source/common/unicode/rep.h
third_party/git/icu/icu4c/source/common/unicode/std_string.h
third_party/git/icu/icu4c/source/common/unicode/utf8.h
third_party/git/icu/icu4c/source/common/unicode/localpointer.h
third_party/git/icu/icu4c/source/common/unicode/uclean.h
third_party/git/icu/icu4c/source/common/unicode/uscript.h
third_party/git/icu/icu4c/source/common/unicode/utypes.h
third_party/git/icu/icu4c/source/common/unicode/unifilt.h
third_party/git/icu/icu4c/source/common/ucol_data.h
third_party/git/icu/icu4c/source/common/locbased.h
third_party/git/icu/icu4c/source/common/cmemory.h
third_party/git/icu/icu4c/source/common/patternprops.h
third_party/git/icu/icu4c/source/common/uresimp.h
third_party/git/icu/icu4c/source/common/ubidi_props_data.h
third_party/git/icu/icu4c/source/common/utracimp.h
third_party/git/icu/icu4c/source/common/norm2allmodes.h
third_party/git/icu/icu4c/source/common/ucptrie_impl.h
third_party/git/icu/icu4c/source/common/msvcres.h
third_party/git/icu/icu4c/source/common/utypeinfo.h
third_party/git/icu/icu4c/source/common/ucnv_cnv.h
third_party/git/icu/icu4c/source/common/static_unicode_sets.h
third_party/git/icu/icu4c/source/common/mlbe.h
third_party/git/icu/icu4c/source/common/sprpimpl.h
third_party/git/icu/icu4c/source/common/cwchar.h
third_party/git/icu/icu4c/source/common/umapfile.h
third_party/git/icu/icu4c/source/common/ulocimp.h
third_party/git/icu/icu4c/source/common/charstr.h
third_party/git/icu/icu4c/source/common/ubidi_props.h
third_party/git/icu/icu4c/source/common/ulayout_props.h
third_party/git/icu/icu4c/source/common/punycode.h
third_party/git/icu/icu4c/source/common/uposixdefs.h
third_party/git/icu/icu4c/source/common/localsvc.h
third_party/git/icu/icu4c/source/common/udataswp.h
third_party/git/icu/icu4c/source/common/cstring.h
third_party/git/icu/icu4c/source/common/propname.h
third_party/git/icu/icu4c/source/common/uenumimp.h
third_party/git/icu/icu4c/source/common/ulist.h
third_party/git/icu/icu4c/source/common/dictionarydata.h
third_party/git/icu/icu4c/source/common/sharedobject.h
third_party/git/icu/icu4c/source/common/serv.h
third_party/git/icu/icu4c/source/common/rbbiscan.h
third_party/git/icu/icu4c/source/common/ucln_imp.h
third_party/git/icu/icu4c/source/common/rbbisetb.h
third_party/git/icu/icu4c/source/common/norm2_nfc_data.h
third_party/git/icu/icu4c/source/common/propname_data.h
third_party/git/icu/icu4c/source/common/ubidiimp.h
third_party/git/icu/icu4c/source/common/ucnvmbcs.h
third_party/git/icu/icu4c/source/common/uvectr64.h
third_party/git/icu/icu4c/source/common/ucmndata.h
third_party/git/icu/icu4c/source/common/rbbirb.h
third_party/git/icu/icu4c/source/common/ubrkimpl.h
third_party/git/icu/icu4c/source/common/ucnv_io.h
third_party/git/icu/icu4c/source/common/util.h
third_party/git/icu/icu4c/source/common/resource.h
third_party/git/icu/icu4c/source/common/bmpset.h
third_party/git/icu/icu4c/source/common/ustr_cnv.h
third_party/git/icu/icu4c/source/common/utrie2_impl.h
third_party/git/icu/icu4c/source/common/ucurrimp.h
third_party/git/icu/icu4c/source/common/ucnv_ext.h
third_party/git/icu/icu4c/source/common/ucase_props_data.h
third_party/git/icu/icu4c/source/common/ucnv_bld.h
third_party/git/icu/icu4c/source/common/normalizer2impl.h
third_party/git/icu/icu4c/source/common/ustrfmt.h
third_party/git/icu/icu4c/source/common/ustrenum.h
third_party/git/icu/icu4c/source/common/uprops.h
third_party/git/icu/icu4c/source/common/ucase.h
third_party/git/icu/icu4c/source/common/unistrappender.h
third_party/git/icu/icu4c/source/common/icuplugimp.h
third_party/git/icu/icu4c/source/common/bytesinkutil.h
third_party/git/icu/icu4c/source/common/brkeng.h
third_party/git/icu/icu4c/source/common/uset_imp.h
third_party/git/icu/icu4c/source/common/mutex.h
third_party/git/icu/icu4c/source/common/rbbitblb.h
third_party/git/icu/icu4c/source/common/locutil.h
third_party/git/icu/icu4c/source/common/ucasemap_imp.h
third_party/git/icu/icu4c/source/common/putilimp.h
third_party/git/icu/icu4c/source/common/restrace.h
third_party/git/icu/icu4c/source/common/rbbirpt.h
third_party/git/icu/icu4c/source/common/uhash.h
third_party/git/icu/icu4c/source/common/utrie.h
third_party/git/icu/icu4c/source/common/ucnv_imp.h
third_party/git/icu/icu4c/source/common/messageimpl.h
third_party/git/icu/icu4c/source/common/capi_helper.h
third_party/git/icu/icu4c/source/common/hash.h
third_party/git/icu/icu4c/source/common/uarrsort.h
third_party/git/icu/icu4c/source/common/cstr.h
third_party/git/icu/icu4c/source/common/ruleiter.h
third_party/git/icu/icu4c/source/common/ucln_cmn.h
third_party/git/icu/icu4c/source/common/uinvchar.h
third_party/git/icu/icu4c/source/common/wintz.h
third_party/git/icu/icu4c/source/common/lsr.h
third_party/git/icu/icu4c/source/common/charstrmap.h

export module icu;

