module;
#undef in
#include <openssl/ssl.h>
#include <git/openssl/ssl/bio_ssl.c>
#include <git/openssl/ssl/d1_lib.c>
#include <git/openssl/ssl/d1_msg.c>
#include <git/openssl/ssl/d1_srtp.c>
#include <git/openssl/ssl/methods.c>
#include <git/openssl/ssl/pqueue.c>
#include <git/openssl/ssl/priority_queue.c>
#include <git/openssl/ssl/quic>
#include <git/openssl/ssl/quic/build.info>
#include <git/openssl/ssl/quic/cc_newreno.c>
#include <git/openssl/ssl/quic/json_enc.c>
#include <git/openssl/ssl/quic/qlog_event_helpers.c>
#include <git/openssl/ssl/quic/qlog.c>
#include <git/openssl/ssl/quic/quic_ackm.c>
#include <git/openssl/ssl/quic/quic_cfq.c>
#include <git/openssl/ssl/quic/quic_channel_local.h>
#include <git/openssl/ssl/quic/quic_channel.c>
#include <git/openssl/ssl/quic/quic_demux.c>
#include <git/openssl/ssl/quic/quic_engine_local.h>
#include <git/openssl/ssl/quic/quic_engine.c>
#include <git/openssl/ssl/quic/quic_fc.c>
#include <git/openssl/ssl/quic/quic_fifd.c>
#include <git/openssl/ssl/quic/quic_impl.c>
#include <git/openssl/ssl/quic/quic_lcidm.c>
#include <git/openssl/ssl/quic/quic_local.h>
#include <git/openssl/ssl/quic/quic_method.c>
#include <git/openssl/ssl/quic/quic_obj_local.h>
#include <git/openssl/ssl/quic/quic_obj.c>
#include <git/openssl/ssl/quic/quic_port_local.h>
#include <git/openssl/ssl/quic/quic_port.c>
#include <git/openssl/ssl/quic/quic_rcidm.c>
#include <git/openssl/ssl/quic/quic_reactor_wait_ctx.c>
#include <git/openssl/ssl/quic/quic_reactor.c>
#include <git/openssl/ssl/quic/quic_record_rx.c>
#include <git/openssl/ssl/quic/quic_record_shared.c>
#include <git/openssl/ssl/quic/quic_record_shared.h>
#include <git/openssl/ssl/quic/quic_record_tx.c>
#include <git/openssl/ssl/quic/quic_record_util.c>
#include <git/openssl/ssl/quic/quic_rstream.c>
#include <git/openssl/ssl/quic/quic_rx_depack.c>
#include <git/openssl/ssl/quic/quic_sf_list.c>
#include <git/openssl/ssl/quic/quic_srt_gen.c>
#include <git/openssl/ssl/quic/quic_srtm.c>
#include <git/openssl/ssl/quic/quic_sstream.c>
#include <git/openssl/ssl/quic/quic_statm.c>
#include <git/openssl/ssl/quic/quic_stream_map.c>
#include <git/openssl/ssl/quic/quic_thread_assist.c>
#include <git/openssl/ssl/quic/quic_tls_api.c>
#include <git/openssl/ssl/quic/quic_tls.c>
#include <git/openssl/ssl/quic/quic_trace.c>
#include <git/openssl/ssl/quic/quic_tserver.c>
#include <git/openssl/ssl/quic/quic_txp.c>
#include <git/openssl/ssl/quic/quic_txpim.c>
#include <git/openssl/ssl/quic/quic_types.c>
#include <git/openssl/ssl/quic/quic_wire_pkt.c>
#include <git/openssl/ssl/quic/quic_wire.c>
#include <git/openssl/ssl/quic/uint_set.c>
#include <git/openssl/ssl/record>
#include <git/openssl/ssl/record/build.info>
#include <git/openssl/ssl/record/methods>
#include <git/openssl/ssl/record/methods/build.info>
#include <git/openssl/ssl/record/methods/dtls_meth.c>
#include <git/openssl/ssl/record/methods/ktls_meth.c>
#include <git/openssl/ssl/record/methods/recmethod_local.h>
#include <git/openssl/ssl/record/methods/ssl3_cbc.c>
#include <git/openssl/ssl/record/methods/ssl3_meth.c>
#include <git/openssl/ssl/record/methods/tls_common.c>
#include <git/openssl/ssl/record/methods/tls_multib.c>
#include <git/openssl/ssl/record/methods/tls_pad.c>
#include <git/openssl/ssl/record/methods/tls1_meth.c>
#include <git/openssl/ssl/record/methods/tls13_meth.c>
#include <git/openssl/ssl/record/methods/tlsany_meth.c>
#include <git/openssl/ssl/record/rec_layer_d1.c>
#include <git/openssl/ssl/record/rec_layer_s3.c>
#include <git/openssl/ssl/record/record_local.h>
#include <git/openssl/ssl/record/record.h>
#include <git/openssl/ssl/rio/poll_builder.c>
#include <git/openssl/ssl/rio/poll_immediate.c>
#include <git/openssl/ssl/rio/rio_notifier.c>
#include <git/openssl/ssl/s3_enc.c>
#include <git/openssl/ssl/s3_lib.c>
#include <git/openssl/ssl/s3_msg.c>
#include <git/openssl/ssl/ssl_asn1.c>
#include <git/openssl/ssl/ssl_cert_comp.c>
#include <git/openssl/ssl/ssl_cert_table.h>
#include <git/openssl/ssl/ssl_cert.c>
#include <git/openssl/ssl/ssl_ciph.c>
#include <git/openssl/ssl/ssl_conf.c>
#include <git/openssl/ssl/ssl_err_legacy.c>
#include <git/openssl/ssl/ssl_init.c>
#include <git/openssl/ssl/ssl_lib.c>
#include <git/openssl/ssl/ssl_local.h>
#include <git/openssl/ssl/ssl_mcnf.c>
#include <git/openssl/ssl/ssl_rsa_legacy.c>
#include <git/openssl/ssl/ssl_rsa.c>
#include <git/openssl/ssl/ssl_sess.c>
#include <git/openssl/ssl/ssl_stat.c>
#include <git/openssl/ssl/ssl_txt.c>
#include <git/openssl/ssl/ssl_utst.c>
#include <git/openssl/ssl/statem/extensions_clnt.c>
#include <git/openssl/ssl/statem/extensions_cust.c>
#include <git/openssl/ssl/statem/extensions_srvr.c>
#include <git/openssl/ssl/statem/extensions.c>
#include <git/openssl/ssl/statem/statem_clnt.c>
#include <git/openssl/ssl/statem/statem_dtls.c>
#include <git/openssl/ssl/statem/statem_lib.c>
#include <git/openssl/ssl/statem/statem_local.h>
#include <git/openssl/ssl/statem/statem_srvr.c>
#include <git/openssl/ssl/statem/statem.c>
#include <git/openssl/ssl/t1_enc.c>
#include <git/openssl/ssl/t1_lib.c>
#include <git/openssl/ssl/t1_trce.c>
#include <git/openssl/ssl/tls_depr.c>
#include <git/openssl/ssl/tls_srp.c>
#include <git/openssl/ssl/tls13_enc.c>

export module openssl;

export
{
    using ::SSL_read;
    using ::SSL_write;
}